services:
  postgres:
    image: postgres:17
    container_name: pdf-to-speech-dev-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pdf-to-speech-dev
    volumes:
      - pdf-to-speech-dev-data:/var/lib/postgresql/data
  postgres-test:
    image: postgres:17
    container_name: pdf-to-speech-test-db
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pdf-to-speech-test
  redis:
    image: redis:7-alpine
    container_name: pdf-to-speech-dev-redis
    ports:
      - "6379:6379"
    volumes:
      - pdf-to-speech-redis-data:/data
    command: redis-server --appendonly yes
  redis-test:
    image: redis:7-alpine
    container_name: pdf-to-speech-test-redis
    ports:
      - "6378:6379"
    command: redis-server --appendonly yes

volumes:
  pdf-to-speech-dev-data:
  pdf-to-speech-redis-data:
